[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "AI-Manager-Python-SDK"
version = "1.0.2"
dependencies = [
    'dataclasses-json==0.6.3',
    'pyjwt==2.8.0'

]
description = "Service client to communicate with an AI_ManAPI"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
readme = {file = "README.md"}

[tool.setuptools.packages]
find = {}  # Scan the project directory with the default parameters
