[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "AI-Manager-Python-SDK"
authors = [
  {name = "Thorsten Atzeni", email = "thorsten.atzeni@brandcompete.com"}
]
maintainers = [
  {name = "Thorsten Atzeni", email = "thorsten.atzeni@brandcompete.com"}
]
description = "Service client to communicate with AI Man-API"
version = "1.0.8"
license = {file = "LICENSE"}
requires-python = ">= 3.8"
dependencies = [
    'dataclasses-json==0.6.3',
    'pyjwt==2.8.0',
    'setuptools==69.0.3',
    'llama-index==0.10.6',
    'pypdf==3.17.4',
    'openpyxl==3.1.2',
    'docx2txt==0.8'
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
readme = "README.md"

[project.urls]
Homepage = "https://www.brandcompete.com"
Repository = "https://github.com/brandcompete/AI-Manager-Python-SDK"

[tool.setuptools.packages]
find = {} 
