[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "AI-Manager-Python-SDK"
description = "Service client to communicate with AI Man-API"
version = "1.0.3"
license = {file = "LICENSE"}
dependencies = [
    'python>=3.8.1,<3.12',
    'dataclasses-json==0.6.3',
    'pyjwt==2.8.0',
    'setuptools==69.0.3',
    'llama-hub==0.0.71',
    'pypdf==3.17.4',
    'openpyxl==3.1.2',
    'docx2txt==0.8'

]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
readme = "README.md"

[tool.setuptools.packages]
find = {} 
